name: pica_crawler

on:
  schedule:
    - cron: "30 9 * * *"
  workflow_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
        with:
          persist-credentials: false
          fetch-depth: 0
      - uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: install dependency
        run: |
          pip install urllib3
          pip install requests
      - name: main logic
        env:
          PICA_SECRET_KEY: ${{secrets.PICA_SECRET_KEY}}
          PICA_ACCOUNT: ${{secrets.PICA_ACCOUNT}}
          PICA_PASSWORD: ${{secrets.PICA_PASSWORD}}
          EMAIL_ACCOUNT: ${{secrets.EMAIL_ACCOUNT}}
          EMAIL_AUTH_CODE: ${{secrets.EMAIL_AUTH_CODE}}
          # 邮箱的smtp服务器地址
          EMAIL_SERVER_HOST: smtp.qq.com
          # 哔咔的分区
          CATEGORIES: CG雜圖,生肉,耽美花園,偽娘哲學,扶他樂園,性轉換,SAO 刀劍神域,WEBTOON
          # CATEGORIES_RULE 过滤规则    INCLUDE: 包含任意一个分区就下载  EXCLUDE: 包含任意一个分区就不下载
          CATEGORIES_RULE: EXCLUDE
          # 每次运行后都会在downloaded.txt里追加本次下载过的漫画
        run: |
          python main.py
          git add downloaded.txt
        # push代码保留本次的下载结果
      - name: commit & push
        uses: actions-go/push@master
        with:
          # 提交代码时配置的git邮箱
          author-email: '1453483448@qq.com'
          # 提交代码时配置的提交人姓名
          author-name: 'phiigross'
          commit-message: 'update downloaded comics'
          remote: origin
          token: ${{ secrets.GIT_TOKEN }}
